In [1]:
%matplotlib inline
import cv2
import matplotlib.pyplot as plt
import logging

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

In [2]:
import mxnet as mx
import numpy as np

from sklearn import svm
from sklearn import metrics
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

import os
import sys
import math
import time
import pickle

proj_dir = os.getcwd()
label_dir = os.path.join(proj_dir, 'emotiondetection/features_labels_lld/labels')
lld_dir = os.path.join(proj_dir, 'emotiondetection/features_labels_lld/lld')

pickle_train_y_list = 'pickle_train_y_list'
pickle_train_x_list = 'pickle_train_x_list'

pickle_test_y_list = 'pickle_test_y_list'
pickle_test_x_list = 'pickle_test_x_list'

In [3]:
train_y_list = pickle.load(open(pickle_train_y_list))
train_x_list = pickle.load(open(pickle_train_x_list))

test_y_list = pickle.load(open(pickle_test_y_list))
test_x_list = pickle.load(open(pickle_test_x_list))

In [4]:
from sklearn.metrics import confusion_matrix
import itertools
def calc_score(test_y_list, predict_y_list):
    print "Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):"
    print 'macro   : ', metrics.precision_recall_fscore_support(test_y_list, predict_y_list, average='macro')
    print 'weighted: ', metrics.precision_recall_fscore_support(test_y_list, predict_y_list, average='weighted')
    print confusion_matrix(test_y_list, predict_y_list)

In [5]:
# z-score normalization
# scaler = preprocessing.StandardScaler().fit(train_x_list)
# train_x_list = scaler.transform(train_x_list)
# test_x_list = scaler.transform(test_x_list)

In [6]:
# PCA whiten
# pca = PCA(n_components='mle', svd_solver='full', whiten=True)
# x_pca = pca.fit(train_x_list)
# train_x_list = pca.transform(train_x_list)
# test_x_list = pca.transform(test_x_list)

In [7]:
# sklearn l1/l2 normalization
# x_normalizer = preprocessing.Normalizer(norm='l2').fit(train_x_list)
# train_x_list = x_normalizer.transform(train_x_list)
# test_x_list = x_normalizer.transform(test_x_list)

In [8]:
# # SMOTE up-sampling training data
# sm = SMOTE(kind='regular')
# train_x_list, train_y_list = sm.fit_sample(train_x_list, train_y_list)
# train_x_list, train_y_list = sm.fit_sample(train_x_list, train_y_list)
# train_x_list, train_y_list = sm.fit_sample(train_x_list, train_y_list)
# train_x_list, train_y_list = sm.fit_sample(train_x_list, train_y_list)
# train_x_list, train_y_list = sm.fit_sample(train_x_list, train_y_list)

# # split training data to 5 different classes
# train_x_lists = [[] for i in range(5)]
# for i in xrange(len(train_y_list)):
#     train_x_lists[int(train_y_list[i])].append(train_x_list[i])
# for i in xrange(5):
#     print 'number of class', i, ':', len(train_x_lists[i])

In [9]:
train_y_list = pickle.load(open(pickle_train_y_list))
train_x_list = pickle.load(open(pickle_train_x_list))

test_y_list = pickle.load(open(pickle_test_y_list))
test_x_list = pickle.load(open(pickle_test_x_list))

# z-score normalization
scaler = preprocessing.StandardScaler().fit(train_x_list)
train_x_list = scaler.transform(train_x_list)
test_x_list = scaler.transform(test_x_list)

In [10]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 0.33,
    1: 2.67 ** 0.33,
    2: 1,
    3: 8.3 ** 0.33,
    4: 7.75 ** 0.33
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )
predict_y_list1 = predict_y_list

start: 2017-01-02 19:28:02
SVC(C=1.0, cache_size=200,
  class_weight={0: 1.8404131569918016, 1: 1.3827660759495979, 2: 1, 3: 2.010461544588641, 4: 1.9654842218759818},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.43437032581322016, 0.33001732248445059, 0.34012622882194549, None)
weighted:  (0.60514395699041468, 0.64817730410560737, 0.60765561020635861, None)
[[ 171  142  287    6    5]
 [  50  475  980    1    2]
 [ 152  472 4660   89    4]
 [  13    5  158   37    2]
 [  43   31  433   30    9]]
end: 2017-01-02 19:29:14


In [11]:
print predict_y_list[:100]
print test_y_list[:100]
print metrics.precision_recall_fscore_support(test_y_list, predict_y_list)

[2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 1 2 2 2 2 2 2 0 1 2 2 2 2 2 2 2 2 2 2 2 1 1
 2 2 2 2 2 2 2 2 1 1 2 1 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 1 2
 1 2 1 2 1 2 1 1 1 2 2 1 1 1 1 1 2 2 2 2 2 2 2 1 1 1]
[2 2 2 2 2 4 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1
 1 2 2 2 2 2 2 2 1 1 2 1 1 2 2 2 0 1 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2
 1 1 1 2 1 1 1 1 1 2 2 1 1 1 2 1 1 2 2 2 2 2 1 1 1 2]
(array([ 0.3986014 ,  0.42222222,  0.71494323,  0.22699387,  0.40909091]), array([ 0.27986907,  0.31498674,  0.86665427,  0.17209302,  0.01648352]), array([ 0.32884615,  0.36080517,  0.78352249,  0.1957672 ,  0.03169014]), array([ 611, 1508, 5377,  215,  546]))


In [12]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 0.4,
    1: 2.67 ** 0.4,
    2: 1,
    3: 8.3 ** 0.4,
    4: 7.75 ** 0.4
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )
predict_y_list2 = predict_y_list

start: 2017-01-02 19:29:14
SVC(C=1.0, cache_size=200,
  class_weight={0: 2.094640469748963, 1: 1.4811686268981117, 2: 1, 3: 2.3314775446267633, 4: 2.2684054445938244},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.41053777172837069, 0.34228042617856314, 0.34914740222390728, None)
weighted:  (0.59901949988912362, 0.64163739857090951, 0.60756400871019145, None)
[[ 182  142  272    6    9]
 [  57  499  945    2    5]
 [ 191  507 4558  107   14]
 [  13    5  149   45    3]
 [  46   32  418   36   14]]
end: 2017-01-02 19:30:27


In [13]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 0.5,
    1: 2.67 ** 0.5,
    2: 1,
    3: 8.3 ** 0.5,
    4: 7.75 ** 0.5
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )
predict_y_list3 = predict_y_list

start: 2017-01-02 19:30:27
SVC(C=1.0, cache_size=200,
  class_weight={0: 2.5199206336708304, 1: 1.6340134638368191, 2: 1, 3: 2.8809720581775866, 4: 2.7838821814150108},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.4042626943866594, 0.3584048191916126, 0.36085679345920862, None)
weighted:  (0.60054714898129358, 0.6315853215453554, 0.60741039606006819, None)
[[ 204  146  240    6   15]
 [  72  529  895    4    8]
 [ 239  571 4403  132   32]
 [  13    5  141   51    5]
 [  52   36  385   45   28]]
end: 2017-01-02 19:31:42


In [14]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 1,
    1: 2.67 ** 1,
    2: 1,
    3: 8.3 ** 1,
    4: 7.75 ** 1
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )
predict_y_list4 = predict_y_list

start: 2017-01-02 19:31:42
SVC(C=1.0, cache_size=200,
  class_weight={0: 6.35, 1: 2.67, 2: 1, 3: 8.3, 4: 7.75}, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.34771895794757218, 0.38614656180344353, 0.35978992049038094, None)
weighted:  (0.59150678158843006, 0.56218965726050629, 0.57334985198892652, None)
[[ 246  162  150    7   46]
 [ 134  672  646    8   48]
 [ 511  834 3595  209  228]
 [  17   11  105   63   19]
 [  65   45  321   49   66]]
end: 2017-01-02 19:33:05


In [15]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 2,
    1: 2.67 ** 2,
    2: 1,
    3: 8.3 ** 2,
    4: 7.75 ** 2
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )
predict_y_list5 = predict_y_list

start: 2017-01-02 19:33:05
SVC(C=1.0, cache_size=200,
  class_weight={0: 40.3225, 1: 7.1289, 2: 1, 3: 68.89000000000001, 4: 60.0625},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.33926852554640358, 0.38659623468274418, 0.35031719895993052, None)
weighted:  (0.58917207746074141, 0.52622017681966815, 0.54556387141094442, None)
[[ 238  205  121    8   39]
 [ 130  803  518   12   45]
 [ 504 1244 3171  221  237]
 [  18   15   98   63   21]
 [  59   79  287   51   70]]
end: 2017-01-02 19:34:35


In [48]:
train_y_list = pickle.load(open(pickle_train_y_list))
train_x_list = pickle.load(open(pickle_train_x_list))

test_y_list = pickle.load(open(pickle_test_y_list))
test_x_list = pickle.load(open(pickle_test_x_list))

# ENN down-sampling training data
from imblearn.under_sampling import EditedNearestNeighbours
from imblearn.under_sampling import TomekLinks 
from imblearn.under_sampling import ClusterCentroids
from imblearn.combine import SMOTEENN
# enn = EditedNearestNeighbours()
# enn = SMOTEENN()
# enn = TomekLinks()
enn = ClusterCentroids()

train_x_list_enn, train_y_list_enn = enn.fit_sample(train_x_list, train_y_list)
# train_x_list_enn, train_y_list_enn = enn.fit_sample(train_x_list_enn, train_y_list_enn)

# split training data to 5 different classes
train_x_lists = [[] for i in range(5)]
train_y_lists = [[] for i in range(5)]
for i in xrange(len(train_y_list_enn)):
    train_x_lists[int(train_y_list_enn[i])].append(train_x_list_enn[i])
    train_y_lists[int(train_y_list_enn[i])].append(train_y_list_enn[i])
for i in xrange(5):
    print 'number of class', i, ':', len(train_x_lists[i])

train_x_lists_enn = train_x_lists
train_y_lists_enn = train_y_lists

number of class 0 : 674
number of class 1 : 674
number of class 2 : 674
number of class 3 : 674
number of class 4 : 674


In [50]:
train_y_list = pickle.load(open(pickle_train_y_list))
train_x_list = pickle.load(open(pickle_train_x_list))

test_y_list = pickle.load(open(pickle_test_y_list))
test_x_list = pickle.load(open(pickle_test_x_list))

# split training data to 5 different classes
train_x_lists = [[] for i in range(5)]
train_y_lists = [[] for i in range(5)]
for i in xrange(len(train_y_list)):
    train_x_lists[int(train_y_list[i])].append(train_x_list[i])
    train_y_lists[int(train_y_list[i])].append(train_y_list[i])
for i in xrange(5):
    print 'number of class', i, ':', len(train_x_lists[i]), len(train_y_lists[i])
print '------------------'

train_x_lists[1] = train_x_lists_enn[1]
train_y_lists[1] = train_y_lists_enn[1]
train_x_lists[2] = train_x_lists_enn[2]
train_y_lists[2] = train_y_lists_enn[2]

train_x_list = np.vstack(train_x_lists)
train_y_list = np.concatenate(train_y_lists)

# split training data to 5 different classes
train_x_lists = [[] for i in range(5)]
for i in xrange(len(train_y_list)):
    train_x_lists[int(train_y_list[i])].append(train_x_list[i])
for i in xrange(5):
    print 'number of class', i, ':', len(train_x_lists[i])

number of class 0 : 881 881
number of class 1 : 2093 2093
number of class 2 : 5590 5590
number of class 3 : 674 674
number of class 4 : 721 721
------------------
number of class 0 : 881
number of class 1 : 674
number of class 2 : 674
number of class 3 : 674
number of class 4 : 721


In [42]:
# train_x_list = train_x_list_enn
# train_y_list = train_y_list_enn

In [51]:
# z-score normalization
scaler = preprocessing.StandardScaler().fit(train_x_list)
train_x_list = scaler.transform(train_x_list)
test_x_list = scaler.transform(test_x_list)

In [52]:
print train_y_list.shape, train_x_list.shape
print test_y_list.shape, test_x_list.shape

(3624,) (3624, 384)
(8257,) (8257, 384)


In [53]:
print train_x_list[0][:10]
print test_x_list[0][:10]

[ 0.67506735  0.0528037   0.67446364 -0.38068081 -0.40528258  0.74205891
 -0.26309741  0.99936794  0.43582439  0.76829528]
[-1.24947057 -0.81926435 -1.24438278 -0.45810469 -0.41422403 -1.29056827
  0.068657   -0.95818242 -0.74776975 -1.29537846]


In [54]:
X = train_x_list
y = train_y_list

In [55]:
# SVM 
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

clf = svm.SVC().fit(X, y)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:32:15
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.29587885079197651, 0.38252983453551564, 0.20100340847025794, None)
weighted:  (0.58115510408094317, 0.18784062007993219, 0.17991859520499798, None)
end: 2016-12-30 20:32:30


In [30]:
# SVM with class_weight='balanced'
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

clf = svm.SVC(class_weight='balanced').fit(X, y)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:15:36
SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.32113274668916331, 0.41193565063273763, 0.31800877496126334, None)
weighted:  (0.61344621207480299, 0.41334625166525374, 0.45524405554992409, None)
end: 2016-12-30 20:16:07


In [31]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 0.33,
    1: 2.67 ** 0.33,
    2: 1,
    3: 8.3 ** 0.33,
    4: 7.75 ** 0.33
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:16:07
SVC(C=1.0, cache_size=200,
  class_weight={0: 1.8404131569918016, 1: 1.3827660759495979, 2: 1, 3: 2.010461544588641, 4: 1.9654842218759818},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.32194985067925602, 0.40413755998548651, 0.29934946231293946, None)
weighted:  (0.61449782844691381, 0.37156352186023978, 0.38581416840209287, None)
end: 2016-12-30 20:16:37


In [32]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 0.4,
    1: 2.67 ** 0.4,
    2: 1,
    3: 8.3 ** 0.4,
    4: 7.75 ** 0.4
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:16:37
SVC(C=1.0, cache_size=200,
  class_weight={0: 2.094640469748963, 1: 1.4811686268981117, 2: 1, 3: 2.3314775446267633, 4: 2.2684054445938244},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.31996519615146141, 0.4034634555604758, 0.29250897985822488, None)
weighted:  (0.62069837927563576, 0.35872592951435145, 0.3713732567840764, None)
end: 2016-12-30 20:17:08


In [33]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 0.5,
    1: 2.67 ** 0.5,
    2: 1,
    3: 8.3 ** 0.5,
    4: 7.75 ** 0.5
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:17:08
SVC(C=1.0, cache_size=200,
  class_weight={0: 2.5199206336708304, 1: 1.6340134638368191, 2: 1, 3: 2.8809720581775866, 4: 2.7838821814150108},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.31663995649598919, 0.40345908120145679, 0.28339466043278255, None)
weighted:  (0.62080248858719667, 0.33934843163376527, 0.34804844980815253, None)
end: 2016-12-30 20:17:39


In [34]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 1,
    1: 2.67 ** 1,
    2: 1,
    3: 8.3 ** 1,
    4: 7.75 ** 1
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:17:39
SVC(C=1.0, cache_size=200,
  class_weight={0: 6.35, 1: 2.67, 2: 1, 3: 8.3, 4: 7.75}, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.30668983152818269, 0.39089494096697652, 0.25133075298765323, None)
weighted:  (0.62477830444406335, 0.28678696863267533, 0.27838346396228048, None)
end: 2016-12-30 20:18:12


In [35]:
print 'start:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

weight = {
    0: 6.35 ** 2,
    1: 2.67 ** 2,
    2: 1,
    3: 8.3 ** 2,
    4: 7.75 ** 2
}

clf = svm.SVC(class_weight=weight).fit(train_x_list, train_y_list)
print clf
predict_y_list = clf.predict(test_x_list)
calc_score(test_y_list, predict_y_list)

print 'end:', time.strftime( '%Y-%m-%d %H:%M:%S', time.localtime( time.time() ) )

start: 2016-12-30 20:18:12
SVC(C=1.0, cache_size=200,
  class_weight={0: 40.3225, 1: 7.1289, 2: 1, 3: 68.89000000000001, 4: 60.0625},
  coef0=0.0, decision_function_shape=None, degree=3, gamma='auto',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
Resulting Accuracy (AVG), Recall (AVG), F-Score (AVG):
macro   :  (0.30877735415219376, 0.3906187830266708, 0.24814798525822557, None)
weighted:  (0.625619325628193, 0.28073150054499213, 0.26179593767554693, None)
end: 2016-12-30 20:18:45


In [36]:
print predict_y_list[:100]

[3 1 3 4 2 0 4 1 1 0 3 3 4 3 1 1 1 4 3 2 2 1 4 1 4 1 3 2 0 1 0 3 0 3 4 1 1
 4 0 0 4 4 0 1 2 1 1 1 1 0 1 1 0 4 1 3 2 1 0 0 1 1 4 1 1 1 1 1 3 1 1 1 1 4
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 4 2 3 1 1 3 1 1 4]


In [37]:
print test_y_list[:100]

[2 2 2 2 2 4 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1
 1 2 2 2 2 2 2 2 1 1 2 1 1 2 2 2 0 1 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2
 1 1 1 2 1 1 1 1 1 2 2 1 1 1 2 1 1 2 2 2 2 2 1 1 1 2]
